# Server Port
server:
  port: 8081

# JSP 위치 설정
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  # Oracle DB 연결 설정 (XE 버전) - 활성화된 설정만 포함
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@192.168.1.212:1521:XE
    username: C##rnb_001
    password: rnb6707

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.OracleDialect

# 인코딩 설정 (한글 깨짐 방지)
http:
  encoding:
    charset: UTF-8  # 이 부분의 들여쓰기를 스페이스로 변경하고, 값도 명확히 지정
    enabled: true
    force: true